In [1]:
from sklearn import metrics
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression

# Historical Scenario

In [46]:
df = pd.read_csv('df.csv',index_col=0) 
df

,XSP.TO_P,XSP.TO_R,XIU.TO_P,XIU.TO_R,XIN.TO_P,XIN.TO_R,XBB.TO_P,XBB.TO_R,XGB.TO_P,XGB.TO_R,XRB.TO_P,XRB.TO_R,XRE.TO_P,XRE.TO_R,Port_P,Port_R
formatted_date,,,,,,,,,,,,,,,,
2006-04-01,13.145290,NaN,11.521857,NaN,17.995522,NaN,16.917009,NaN,NaN,NaN,14.437650,NaN,6.142775,NaN,NaN,NaN
2006-05-01,12.707119,-0.033333,11.153104,-0.032005,16.989994,-0.055877,16.982298,0.003859,NaN,NaN,14.296542,-0.009774,6.151716,0.001456,NaN,NaN
2006-06-01,12.794751,0.006896,11.037451,-0.010370,17.191097,0.011837,16.697371,-0.016778,NaN,NaN,14.051461,-0.017143,6.120422,-0.005087,NaN,NaN
2006-07-01,12.810687,0.001246,11.291711,0.023036,17.232704,0.002420,17.248827,0.033027,NaN,NaN,14.674636,0.044349,6.482049,0.059085,NaN,NaN
2006-08-01,13.081561,0.021144,11.542490,0.022209,17.718132,0.028169,17.561024,0.018100,NaN,NaN,14.960310,0.019467,6.672697,0.029412,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-01,40.849056,0.027277,26.603354,0.036510,27.332333,0.027902,31.725668,-0.027332,22.031994,-0.031403,25.542923,-0.042799,16.469028,0.038749,120630.995336,0.006222
2021-03-01,42.650196,0.044093,28.012825,0.052981,28.717251,0.050670,31.317741,-0.012858,21.713200,-0.014470,25.324438,-0.008554,17.255177,0.047735,123727.171566,0.025667
2021-04-01,44.809574,0.050630,28.658510,0.023050,29.033804,0.011023,31.326403,0.000277,21.741892,0.001321,24.817949,-0.020000,18.062016,0.046759,130937.071944,0.018547
2021-05-01,44.998646,0.004219,29.542603,0.030849,29.696587,0.022828,31.514418,0.006002,21.864332,0.005632,25.672029,0.034414,18.537380,0.026318,133373.665904,0.018609
2021-06-01,45.953945,0.021230,30.530001,0.033423,29.736155,0.001332,31.852020,0.010713,22.127020,0.012014,25.920309,0.009671,19.163364,0.033769,135705.400744,0.017483

In [50]:
#Each Asset Returns
df_R = pd.read_csv('df_R.csv') 
df_R

,date,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
0,2006-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006-05-01,-0.033333,-0.032005,-0.055877,0.003859,NaN,-0.009774,0.001456
2,2006-06-01,0.006896,-0.010370,0.011837,-0.016778,NaN,-0.017143,-0.005087
3,2006-07-01,0.001246,0.023036,0.002420,0.033027,NaN,0.044349,0.059085
4,2006-08-01,0.021144,0.022209,0.028169,0.018100,NaN,0.019467,0.029412
...,...,...,...,...,...,...,...,...
178,2021-02-01,0.027277,0.036510,0.027902,-0.027332,-0.031403,-0.042799,0.038749
179,2021-03-01,0.044093,0.052981,0.050670,-0.012858,-0.014470,-0.008554,0.047735
180,2021-04-01,0.050630,0.023050,0.011023,0.000277,0.001321,-0.020000,0.046759
181,2021-05-01,0.004219,0.030849,0.022828,0.006002,0.005632,0.034414,0.026318
182,2021-06-01,0.021230,0.033423,0.001332,0.010713,0.012014,0.009671,0.033769

In [51]:
report_date = '2021-06-01'

## Great Recession : 2007-07-12 ~ 2009-09-02

In [52]:
open_day='2007-07-12'
close_day='2009-09-02'
con1=df_R['date']>=open_day
con2=df_R['date']<=close_day
Great_recession=df_R[con1&con2]
Great_recession

,date,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
16,2007-08-01,0.011475,-0.008830,-0.003507,0.009950,0.010775,-0.005420,0.020196
17,2007-09-01,0.032955,0.026850,0.016895,-0.004926,-0.003045,0.016894,0.019157
18,2007-10-01,0.014644,0.045350,0.029076,0.017006,0.016859,0.003752,-0.033252
19,2007-11-01,-0.046392,-0.053670,-0.045409,0.011959,0.017713,-0.003738,-0.031434
20,2007-12-01,-0.017838,0.005957,-0.038760,-0.002086,-0.003481,0.017149,-0.035836
21,2008-01-01,-0.050061,-0.040450,-0.085962,0.016032,0.015824,0.002308,-0.037990
22,2008-02-01,-0.030534,0.033592,-0.028688,0.012136,0.009926,0.023404,-0.002242
23,2008-03-01,-0.004240,-0.018750,-0.022363,-0.002399,0.006387,0.040541,-0.006742
24,2008-04-01,0.050487,0.064680,0.062150,0.005007,-0.000715,-0.018482,0.036814
25,2008-05-01,0.010423,0.064462,0.019098,-0.000346,0.000000,0.031552,0.024194
26,2008-06-01,-0.095129,-0.026551,-0.113238,-0.008984,-0.008391,0.016774,-0.068002
27,2008-07-01,0.000103,-0.045418,-0.009269,0.019110,0.017818,0.011825,0.001648
28,2008-08-01,0.016592,0.010027,0.008295,0.005538,0.010381,0.005340,0.048324
29,2008-09-01,-0.082862,-0.129782,-0.090951,-0.030293,-0.028376,-0.097055,-0.104089
30,2008-10-01,-0.208761,-0.164559,-0.185520,0.001108,0.001842,-0.044920,-0.211617
31,2008-11-01,-0.048443,-0.064386,-0.003087,0.024408,0.028456,-0.017917,-0.090129
32,2008-12-01,-0.031818,-0.025807,-0.028483,0.020672,0.034585,0.050171,-0.035377
33,2009-01-01,-0.082629,-0.025327,-0.096240,-0.001990,-0.006149,-0.006211,0.034566
34,2009-02-01,-0.108495,-0.060975,-0.074048,0.009739,0.001941,-0.016667,-0.072482
35,2009-03-01,0.080367,0.074675,0.054075,0.005856,0.004359,0.091526,-0.037086
36,2009-04-01,0.092455,0.083779,0.098266,0.009797,0.007886,-0.027951,0.110740
37,2009-05-01,0.050584,0.125702,0.052631,0.000000,-0.014017,0.010117,0.143037
38,2009-06-01,-0.012037,-0.013724,-0.030000,0.002400,0.002452,0.010016,0.013172
39,2009-07-01,0.084303,0.050263,0.094972,0.015744,0.010525,0.048166,0.067950
40,2009-08-01,0.033130,-0.001820,0.039497,0.007831,0.008309,-0.007056,0.080042
41,2009-09-01,0.032911,0.035866,0.020150,0.002364,-0.000485,0.002538,0.058710

In [55]:
Great_recession.to_csv('recession.csv',encoding='utf-8',index=False)

In [56]:
Great_recession=pd.read_csv('recession.csv',index_col=0)
Great_recession

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2007-08-01,0.011475,-0.008830,-0.003507,0.009950,0.010775,-0.005420,0.020196
2007-09-01,0.032955,0.026850,0.016895,-0.004926,-0.003045,0.016894,0.019157
2007-10-01,0.014644,0.045350,0.029076,0.017006,0.016859,0.003752,-0.033252
2007-11-01,-0.046392,-0.053670,-0.045409,0.011959,0.017713,-0.003738,-0.031434
2007-12-01,-0.017838,0.005957,-0.038760,-0.002086,-0.003481,0.017149,-0.035836
2008-01-01,-0.050061,-0.040450,-0.085962,0.016032,0.015824,0.002308,-0.037990
2008-02-01,-0.030534,0.033592,-0.028688,0.012136,0.009926,0.023404,-0.002242
2008-03-01,-0.004240,-0.018750,-0.022363,-0.002399,0.006387,0.040541,-0.006742
2008-04-01,0.050487,0.064680,0.062150,0.005007,-0.000715,-0.018482,0.036814
2008-05-01,0.010423,0.064462,0.019098,-0.000346,0.000000,0.031552,0.024194
2008-06-01,-0.095129,-0.026551,-0.113238,-0.008984,-0.008391,0.016774,-0.068002
2008-07-01,0.000103,-0.045418,-0.009269,0.019110,0.017818,0.011825,0.001648
2008-08-01,0.016592,0.010027,0.008295,0.005538,0.010381,0.005340,0.048324
2008-09-01,-0.082862,-0.129782,-0.090951,-0.030293,-0.028376,-0.097055,-0.104089
2008-10-01,-0.208761,-0.164559,-0.185520,0.001108,0.001842,-0.044920,-0.211617
2008-11-01,-0.048443,-0.064386,-0.003087,0.024408,0.028456,-0.017917,-0.090129
2008-12-01,-0.031818,-0.025807,-0.028483,0.020672,0.034585,0.050171,-0.035377
2009-01-01,-0.082629,-0.025327,-0.096240,-0.001990,-0.006149,-0.006211,0.034566
2009-02-01,-0.108495,-0.060975,-0.074048,0.009739,0.001941,-0.016667,-0.072482
2009-03-01,0.080367,0.074675,0.054075,0.005856,0.004359,0.091526,-0.037086
2009-04-01,0.092455,0.083779,0.098266,0.009797,0.007886,-0.027951,0.110740
2009-05-01,0.050584,0.125702,0.052631,0.000000,-0.014017,0.010117,0.143037
2009-06-01,-0.012037,-0.013724,-0.030000,0.002400,0.002452,0.010016,0.013172
2009-07-01,0.084303,0.050263,0.094972,0.015744,0.010525,0.048166,0.067950
2009-08-01,0.033130,-0.001820,0.039497,0.007831,0.008309,-0.007056,0.080042
2009-09-01,0.032911,0.035866,0.020150,0.002364,-0.000485,0.002538,0.058710

In [58]:
XSPTO_R=  df['XSP.TO_P'].iloc[-1] * Great_recession["XSP.TO_R"]
XSPTO_R = XSPTO_R.to_frame(name='XSP.TO_R')

XIUTO_R=  df['XIU.TO_P'].iloc[-1] * Great_recession["XIU.TO_R"]
XIUTO_R = XIUTO_R.to_frame(name='XIU.TO_R')

XINTO_R=  df['XIN.TO_P'].iloc[-1] * Great_recession["XIN.TO_R"]
XINTO_R = XINTO_R.to_frame(name='XIN.TO_R')

XBBTO_R=  df['XBB.TO_P'].iloc[-1] * Great_recession["XBB.TO_R"]
XBBTO_R = XBBTO_R.to_frame(name='XBB.TO_R')

XGBTO_R=  df['XGB.TO_P'].iloc[-1] * Great_recession["XGB.TO_R"]
XGBTO_R = XGBTO_R.to_frame(name='XGB.TO_R')

XRBTO_R=  df['XRB.TO_P'].iloc[-1] * Great_recession["XRB.TO_R"]
XRBTO_R = XRBTO_R.to_frame(name='XRB.TO_R')

XRETO_R=  df['XRE.TO_P'].iloc[-1] * Great_recession["XRE.TO_R"]
XRETO_R = XRETO_R.to_frame(name='XRE.TO_R')

In [61]:
Great_recession = XSPTO_R.merge(XIUTO_R, on='date').merge(XINTO_R, on='date').merge(XBBTO_R, on='date').merge(XGBTO_R, on='date').merge(XRBTO_R, on='date').merge(XRETO_R, on='date')
Great_recession

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2007-08-01,0.527337,-0.269571,-0.104295,0.316927,0.238412,-0.140499,0.387029
2007-09-01,1.514423,0.819744,0.502398,-0.156918,-0.067381,0.437889,0.367115
2007-10-01,0.672969,1.384551,0.864607,0.541677,0.373031,0.097249,-0.637220
2007-11-01,-2.131878,-1.638552,-1.350276,0.380932,0.391938,-0.096885,-0.602373
2007-12-01,-0.819716,0.181865,-1.152567,-0.066429,-0.077019,0.444517,-0.686732
2008-01-01,-2.300520,-1.234941,-2.556188,0.510659,0.350134,0.059826,-0.728018
2008-02-01,-1.403173,1.025565,-0.853081,0.386563,0.219636,0.606644,-0.042962
2008-03-01,-0.194836,-0.572441,-0.664990,-0.076399,0.141325,1.050827,-0.129201
2008-04-01,2.320057,1.974688,1.848094,0.159481,-0.015819,-0.479053,0.705478
2008-05-01,0.478963,1.968020,0.567890,-0.011006,0.000000,0.817843,0.463631
2008-06-01,-4.371555,-0.810593,-3.367254,-0.286148,-0.185672,0.434776,-1.303156
2008-07-01,0.004727,-1.386609,-0.275639,0.608700,0.394256,0.306512,0.031589
2008-08-01,0.762467,0.306124,0.246662,0.176400,0.229694,0.138407,0.926057
2008-09-01,-3.807852,-3.962239,-2.704522,-0.964882,-0.627877,-2.515691,-1.994700
2008-10-01,-9.593390,-5.023979,-5.516660,0.035298,0.040766,-1.164339,-4.055292
2008-11-01,-2.226143,-1.965716,-0.091783,0.777446,0.629647,-0.464415,-1.727177
2008-12-01,-1.462178,-0.787879,-0.846974,0.658459,0.765255,1.300448,-0.677939
2009-01-01,-3.797144,-0.773234,-2.861796,-0.063390,-0.136055,-0.160995,0.662394
2009-02-01,-4.985782,-1.861576,-2.201901,0.310211,0.042941,-0.432007,-1.388998
2009-03-01,3.693201,2.279842,1.607974,0.186530,0.096445,2.372373,-0.710685
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083

In [62]:
Great_recession["Portfolio"] = Great_recession.sum(axis=1)
Great_recession

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2007-08-01,0.527337,-0.269571,-0.104295,0.316927,0.238412,-0.140499,0.387029,0.955339
2007-09-01,1.514423,0.819744,0.502398,-0.156918,-0.067381,0.437889,0.367115,3.417269
2007-10-01,0.672969,1.384551,0.864607,0.541677,0.373031,0.097249,-0.637220,3.296863
2007-11-01,-2.131878,-1.638552,-1.350276,0.380932,0.391938,-0.096885,-0.602373,-5.047093
2007-12-01,-0.819716,0.181865,-1.152567,-0.066429,-0.077019,0.444517,-0.686732,-2.176080
2008-01-01,-2.300520,-1.234941,-2.556188,0.510659,0.350134,0.059826,-0.728018,-5.899048
2008-02-01,-1.403173,1.025565,-0.853081,0.386563,0.219636,0.606644,-0.042962,-0.060807
2008-03-01,-0.194836,-0.572441,-0.664990,-0.076399,0.141325,1.050827,-0.129201,-0.445716
2008-04-01,2.320057,1.974688,1.848094,0.159481,-0.015819,-0.479053,0.705478,6.512926
2008-05-01,0.478963,1.968020,0.567890,-0.011006,0.000000,0.817843,0.463631,4.285342
2008-06-01,-4.371555,-0.810593,-3.367254,-0.286148,-0.185672,0.434776,-1.303156,-9.889603
2008-07-01,0.004727,-1.386609,-0.275639,0.608700,0.394256,0.306512,0.031589,-0.316464
2008-08-01,0.762467,0.306124,0.246662,0.176400,0.229694,0.138407,0.926057,2.785811
2008-09-01,-3.807852,-3.962239,-2.704522,-0.964882,-0.627877,-2.515691,-1.994700,-16.577764
2008-10-01,-9.593390,-5.023979,-5.516660,0.035298,0.040766,-1.164339,-4.055292,-25.277596
2008-11-01,-2.226143,-1.965716,-0.091783,0.777446,0.629647,-0.464415,-1.727177,-5.068140
2008-12-01,-1.462178,-0.787879,-0.846974,0.658459,0.765255,1.300448,-0.677939,-1.050808
2009-01-01,-3.797144,-0.773234,-2.861796,-0.063390,-0.136055,-0.160995,0.662394,-7.130222
2009-02-01,-4.985782,-1.861576,-2.201901,0.310211,0.042941,-0.432007,-1.388998,-10.517111
2009-03-01,3.693201,2.279842,1.607974,0.186530,0.096445,2.372373,-0.710685,9.525680
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160,11.612673
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070,10.420429
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414,-1.221500
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156,11.517688
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873,4.425658
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083,4.461988

In [63]:
Great_recession.iloc[0,7]= 0.955339 + 135705.400744
Great_recession

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2007-08-01,0.527337,-0.269571,-0.104295,0.316927,0.238412,-0.140499,0.387029,135706.356083
2007-09-01,1.514423,0.819744,0.502398,-0.156918,-0.067381,0.437889,0.367115,3.417269
2007-10-01,0.672969,1.384551,0.864607,0.541677,0.373031,0.097249,-0.637220,3.296863
2007-11-01,-2.131878,-1.638552,-1.350276,0.380932,0.391938,-0.096885,-0.602373,-5.047093
2007-12-01,-0.819716,0.181865,-1.152567,-0.066429,-0.077019,0.444517,-0.686732,-2.176080
2008-01-01,-2.300520,-1.234941,-2.556188,0.510659,0.350134,0.059826,-0.728018,-5.899048
2008-02-01,-1.403173,1.025565,-0.853081,0.386563,0.219636,0.606644,-0.042962,-0.060807
2008-03-01,-0.194836,-0.572441,-0.664990,-0.076399,0.141325,1.050827,-0.129201,-0.445716
2008-04-01,2.320057,1.974688,1.848094,0.159481,-0.015819,-0.479053,0.705478,6.512926
2008-05-01,0.478963,1.968020,0.567890,-0.011006,0.000000,0.817843,0.463631,4.285342
2008-06-01,-4.371555,-0.810593,-3.367254,-0.286148,-0.185672,0.434776,-1.303156,-9.889603
2008-07-01,0.004727,-1.386609,-0.275639,0.608700,0.394256,0.306512,0.031589,-0.316464
2008-08-01,0.762467,0.306124,0.246662,0.176400,0.229694,0.138407,0.926057,2.785811
2008-09-01,-3.807852,-3.962239,-2.704522,-0.964882,-0.627877,-2.515691,-1.994700,-16.577764
2008-10-01,-9.593390,-5.023979,-5.516660,0.035298,0.040766,-1.164339,-4.055292,-25.277596
2008-11-01,-2.226143,-1.965716,-0.091783,0.777446,0.629647,-0.464415,-1.727177,-5.068140
2008-12-01,-1.462178,-0.787879,-0.846974,0.658459,0.765255,1.300448,-0.677939,-1.050808
2009-01-01,-3.797144,-0.773234,-2.861796,-0.063390,-0.136055,-0.160995,0.662394,-7.130222
2009-02-01,-4.985782,-1.861576,-2.201901,0.310211,0.042941,-0.432007,-1.388998,-10.517111
2009-03-01,3.693201,2.279842,1.607974,0.186530,0.096445,2.372373,-0.710685,9.525680
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160,11.612673
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070,10.420429
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414,-1.221500
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156,11.517688
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873,4.425658
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083,4.461988

In [64]:
Great_recession['Portfolio'] = np.cumsum(Great_recession['Portfolio'])
Great_recession

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2007-08-01,0.527337,-0.269571,-0.104295,0.316927,0.238412,-0.140499,0.387029,135706.356083
2007-09-01,1.514423,0.819744,0.502398,-0.156918,-0.067381,0.437889,0.367115,135709.773352
2007-10-01,0.672969,1.384551,0.864607,0.541677,0.373031,0.097249,-0.637220,135713.070215
2007-11-01,-2.131878,-1.638552,-1.350276,0.380932,0.391938,-0.096885,-0.602373,135708.023122
2007-12-01,-0.819716,0.181865,-1.152567,-0.066429,-0.077019,0.444517,-0.686732,135705.847042
2008-01-01,-2.300520,-1.234941,-2.556188,0.510659,0.350134,0.059826,-0.728018,135699.947994
2008-02-01,-1.403173,1.025565,-0.853081,0.386563,0.219636,0.606644,-0.042962,135699.887187
2008-03-01,-0.194836,-0.572441,-0.664990,-0.076399,0.141325,1.050827,-0.129201,135699.441471
2008-04-01,2.320057,1.974688,1.848094,0.159481,-0.015819,-0.479053,0.705478,135705.954397
2008-05-01,0.478963,1.968020,0.567890,-0.011006,0.000000,0.817843,0.463631,135710.239739
2008-06-01,-4.371555,-0.810593,-3.367254,-0.286148,-0.185672,0.434776,-1.303156,135700.350137
2008-07-01,0.004727,-1.386609,-0.275639,0.608700,0.394256,0.306512,0.031589,135700.033673
2008-08-01,0.762467,0.306124,0.246662,0.176400,0.229694,0.138407,0.926057,135702.819484
2008-09-01,-3.807852,-3.962239,-2.704522,-0.964882,-0.627877,-2.515691,-1.994700,135686.241720
2008-10-01,-9.593390,-5.023979,-5.516660,0.035298,0.040766,-1.164339,-4.055292,135660.964124
2008-11-01,-2.226143,-1.965716,-0.091783,0.777446,0.629647,-0.464415,-1.727177,135655.895984
2008-12-01,-1.462178,-0.787879,-0.846974,0.658459,0.765255,1.300448,-0.677939,135654.845175
2009-01-01,-3.797144,-0.773234,-2.861796,-0.063390,-0.136055,-0.160995,0.662394,135647.714954
2009-02-01,-4.985782,-1.861576,-2.201901,0.310211,0.042941,-0.432007,-1.388998,135637.197843
2009-03-01,3.693201,2.279842,1.607974,0.186530,0.096445,2.372373,-0.710685,135646.723523
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160,135658.336196
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070,135668.756625
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414,135667.535125
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156,135679.052813
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873,135683.478471
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083,135687.940459

In [66]:
Great_recession.to_csv('great_recession.csv')

## Covid-19 Period: 2020-01-23 ~ 2021-06-21

In [67]:
open_day='2020-01-23'
close_day='2021-06-21'
con1=df_R['date']>=open_day
con2=df_R['date']<=close_day
covid19=df_R[con1&con2]
covid19

,date,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
166,2020-02-01,-0.080473,-0.061350,-0.071322,0.005312,0.007174,0.012002,-0.034979
167,2020-03-01,-0.136475,-0.150315,-0.141200,-0.033476,-0.005633,-0.076894,-0.272430
168,2020-04-01,0.124026,0.092978,0.055892,0.052750,0.032464,0.051803,0.061883
169,2020-05-01,0.048235,0.019052,0.052051,0.003723,0.001387,0.013002,-0.022028
170,2020-06-01,0.012030,0.033311,0.014675,0.017953,0.013425,0.016336,0.030267
171,2020-07-01,0.064593,0.041189,-0.010238,0.014390,0.011574,0.057263,0.012595
172,2020-08-01,0.065823,0.014682,0.037553,-0.014118,-0.015537,-0.008029,-0.018741
173,2020-09-01,-0.039588,-0.012715,-0.008133,0.003909,0.004744,0.001472,-0.008430
174,2020-10-01,-0.024732,-0.034865,-0.034850,-0.008661,-0.008086,-0.005143,-0.023549
175,2020-11-01,0.105663,0.097748,0.121070,0.011783,0.006898,0.017356,0.172612
176,2020-12-01,0.029307,0.017109,0.017431,0.005098,0.002150,-0.008338,-0.023585
177,2021-01-01,-0.004031,-0.001918,0.009474,-0.013138,-0.012872,-0.013502,0.003218
178,2021-02-01,0.027277,0.036510,0.027902,-0.027332,-0.031403,-0.042799,0.038749
179,2021-03-01,0.044093,0.052981,0.050670,-0.012858,-0.014470,-0.008554,0.047735
180,2021-04-01,0.050630,0.023050,0.011023,0.000277,0.001321,-0.020000,0.046759
181,2021-05-01,0.004219,0.030849,0.022828,0.006002,0.005632,0.034414,0.026318
182,2021-06-01,0.021230,0.033423,0.001332,0.010713,0.012014,0.009671,0.033769

In [70]:
covid19.to_csv('covid19.csv',encoding='utf-8',index=False)

In [71]:
covid19=pd.read_csv('covid19.csv',index_col=0)
covid19

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2020-02-01,-0.080473,-0.061350,-0.071322,0.005312,0.007174,0.012002,-0.034979
2020-03-01,-0.136475,-0.150315,-0.141200,-0.033476,-0.005633,-0.076894,-0.272430
2020-04-01,0.124026,0.092978,0.055892,0.052750,0.032464,0.051803,0.061883
2020-05-01,0.048235,0.019052,0.052051,0.003723,0.001387,0.013002,-0.022028
2020-06-01,0.012030,0.033311,0.014675,0.017953,0.013425,0.016336,0.030267
2020-07-01,0.064593,0.041189,-0.010238,0.014390,0.011574,0.057263,0.012595
2020-08-01,0.065823,0.014682,0.037553,-0.014118,-0.015537,-0.008029,-0.018741
2020-09-01,-0.039588,-0.012715,-0.008133,0.003909,0.004744,0.001472,-0.008430
2020-10-01,-0.024732,-0.034865,-0.034850,-0.008661,-0.008086,-0.005143,-0.023549
2020-11-01,0.105663,0.097748,0.121070,0.011783,0.006898,0.017356,0.172612
2020-12-01,0.029307,0.017109,0.017431,0.005098,0.002150,-0.008338,-0.023585
2021-01-01,-0.004031,-0.001918,0.009474,-0.013138,-0.012872,-0.013502,0.003218
2021-02-01,0.027277,0.036510,0.027902,-0.027332,-0.031403,-0.042799,0.038749
2021-03-01,0.044093,0.052981,0.050670,-0.012858,-0.014470,-0.008554,0.047735
2021-04-01,0.050630,0.023050,0.011023,0.000277,0.001321,-0.020000,0.046759
2021-05-01,0.004219,0.030849,0.022828,0.006002,0.005632,0.034414,0.026318
2021-06-01,0.021230,0.033423,0.001332,0.010713,0.012014,0.009671,0.033769

In [72]:
XSPTO_R=  df['XSP.TO_P'].iloc[-1] * covid19["XSP.TO_R"]
XSPTO_R = XSPTO_R.to_frame(name='XSP.TO_R')

XIUTO_R=  df['XIU.TO_P'].iloc[-1] * covid19["XIU.TO_R"]
XIUTO_R = XIUTO_R.to_frame(name='XIU.TO_R')

XINTO_R=  df['XIN.TO_P'].iloc[-1] * covid19["XIN.TO_R"]
XINTO_R = XINTO_R.to_frame(name='XIN.TO_R')

XBBTO_R=  df['XBB.TO_P'].iloc[-1] * covid19["XBB.TO_R"]
XBBTO_R = XBBTO_R.to_frame(name='XBB.TO_R')

XGBTO_R=  df['XGB.TO_P'].iloc[-1] * covid19["XGB.TO_R"]
XGBTO_R = XGBTO_R.to_frame(name='XGB.TO_R')

XRBTO_R=  df['XRB.TO_P'].iloc[-1] * covid19["XRB.TO_R"]
XRBTO_R = XRBTO_R.to_frame(name='XRB.TO_R')

XRETO_R=  df['XRE.TO_P'].iloc[-1] * covid19["XRE.TO_R"]
XRETO_R = XRETO_R.to_frame(name='XRE.TO_R')

In [73]:
covid19 = XSPTO_R.merge(XIUTO_R, on='date').merge(XINTO_R, on='date').merge(XBBTO_R, on='date').merge(XGBTO_R, on='date').merge(XRBTO_R, on='date').merge(XRETO_R, on='date')
covid19

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2020-02-01,-3.698041,-1.873008,-2.120852,0.169184,0.158738,0.311084,-0.670321
2020-03-01,-6.271565,-4.589115,-4.198747,-1.066292,-0.124649,-1.993106,-5.220678
2020-04-01,5.699461,2.838621,1.662015,1.680186,0.718323,1.342742,1.185895
2020-05-01,2.216573,0.581653,1.547801,0.118571,0.030696,0.337028,-0.422132
2020-06-01,0.552825,1.016980,0.436379,0.571846,0.297064,0.423434,0.580018
2020-07-01,2.968301,1.257501,-0.304450,0.458357,0.256106,1.484263,0.241354
2020-08-01,3.024817,0.448239,1.116674,-0.449694,-0.343796,-0.208117,-0.359134
2020-09-01,-1.819236,-0.388196,-0.241857,0.124523,0.104978,0.038144,-0.161556
2020-10-01,-1.136534,-1.064418,-1.036312,-0.275865,-0.178925,-0.133316,-0.451285
2020-11-01,4.855654,2.984232,3.600170,0.375301,0.152638,0.449873,3.307836
2020-12-01,1.346763,0.522352,0.518326,0.162377,0.047563,-0.216131,-0.451961
2021-01-01,-0.185244,-0.058554,0.281723,-0.418470,-0.284830,-0.349969,0.061672
2021-02-01,1.253497,1.114661,0.829692,-0.870595,-0.694846,-1.109356,0.742562
2021-03-01,2.026227,1.617509,1.506719,-0.409551,-0.320169,-0.221713,0.914762
2021-04-01,2.326647,0.703705,0.327785,0.008809,0.029239,-0.518406,0.896064
2021-05-01,0.193900,0.941826,0.678816,0.191170,0.124609,0.892017,0.504351
2021-06-01,0.975580,1.020400,0.039621,0.341219,0.265844,0.250681,0.647123

In [74]:
covid19["Portfolio"] = covid19.sum(axis=1)
covid19

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2020-02-01,-3.698041,-1.873008,-2.120852,0.169184,0.158738,0.311084,-0.670321,-7.723216
2020-03-01,-6.271565,-4.589115,-4.198747,-1.066292,-0.124649,-1.993106,-5.220678,-23.464152
2020-04-01,5.699461,2.838621,1.662015,1.680186,0.718323,1.342742,1.185895,15.127243
2020-05-01,2.216573,0.581653,1.547801,0.118571,0.030696,0.337028,-0.422132,4.410189
2020-06-01,0.552825,1.016980,0.436379,0.571846,0.297064,0.423434,0.580018,3.878547
2020-07-01,2.968301,1.257501,-0.304450,0.458357,0.256106,1.484263,0.241354,6.361433
2020-08-01,3.024817,0.448239,1.116674,-0.449694,-0.343796,-0.208117,-0.359134,3.228989
2020-09-01,-1.819236,-0.388196,-0.241857,0.124523,0.104978,0.038144,-0.161556,-2.343200
2020-10-01,-1.136534,-1.064418,-1.036312,-0.275865,-0.178925,-0.133316,-0.451285,-4.276655
2020-11-01,4.855654,2.984232,3.600170,0.375301,0.152638,0.449873,3.307836,15.725704
2020-12-01,1.346763,0.522352,0.518326,0.162377,0.047563,-0.216131,-0.451961,1.929288
2021-01-01,-0.185244,-0.058554,0.281723,-0.418470,-0.284830,-0.349969,0.061672,-0.953671
2021-02-01,1.253497,1.114661,0.829692,-0.870595,-0.694846,-1.109356,0.742562,1.265616
2021-03-01,2.026227,1.617509,1.506719,-0.409551,-0.320169,-0.221713,0.914762,5.113784
2021-04-01,2.326647,0.703705,0.327785,0.008809,0.029239,-0.518406,0.896064,3.773843
2021-05-01,0.193900,0.941826,0.678816,0.191170,0.124609,0.892017,0.504351,3.526688
2021-06-01,0.975580,1.020400,0.039621,0.341219,0.265844,0.250681,0.647123,3.540467

In [75]:
covid19.iloc[0,7]= -7.723216 + 135705.400744
covid19

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2020-02-01,-3.698041,-1.873008,-2.120852,0.169184,0.158738,0.311084,-0.670321,135697.677528
2020-03-01,-6.271565,-4.589115,-4.198747,-1.066292,-0.124649,-1.993106,-5.220678,-23.464152
2020-04-01,5.699461,2.838621,1.662015,1.680186,0.718323,1.342742,1.185895,15.127243
2020-05-01,2.216573,0.581653,1.547801,0.118571,0.030696,0.337028,-0.422132,4.410189
2020-06-01,0.552825,1.016980,0.436379,0.571846,0.297064,0.423434,0.580018,3.878547
2020-07-01,2.968301,1.257501,-0.304450,0.458357,0.256106,1.484263,0.241354,6.361433
2020-08-01,3.024817,0.448239,1.116674,-0.449694,-0.343796,-0.208117,-0.359134,3.228989
2020-09-01,-1.819236,-0.388196,-0.241857,0.124523,0.104978,0.038144,-0.161556,-2.343200
2020-10-01,-1.136534,-1.064418,-1.036312,-0.275865,-0.178925,-0.133316,-0.451285,-4.276655
2020-11-01,4.855654,2.984232,3.600170,0.375301,0.152638,0.449873,3.307836,15.725704
2020-12-01,1.346763,0.522352,0.518326,0.162377,0.047563,-0.216131,-0.451961,1.929288
2021-01-01,-0.185244,-0.058554,0.281723,-0.418470,-0.284830,-0.349969,0.061672,-0.953671
2021-02-01,1.253497,1.114661,0.829692,-0.870595,-0.694846,-1.109356,0.742562,1.265616
2021-03-01,2.026227,1.617509,1.506719,-0.409551,-0.320169,-0.221713,0.914762,5.113784
2021-04-01,2.326647,0.703705,0.327785,0.008809,0.029239,-0.518406,0.896064,3.773843
2021-05-01,0.193900,0.941826,0.678816,0.191170,0.124609,0.892017,0.504351,3.526688
2021-06-01,0.975580,1.020400,0.039621,0.341219,0.265844,0.250681,0.647123,3.540467

In [76]:
covid19['Portfolio'] = np.cumsum(covid19['Portfolio'])
covid19

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2020-02-01,-3.698041,-1.873008,-2.120852,0.169184,0.158738,0.311084,-0.670321,135697.677528
2020-03-01,-6.271565,-4.589115,-4.198747,-1.066292,-0.124649,-1.993106,-5.220678,135674.213376
2020-04-01,5.699461,2.838621,1.662015,1.680186,0.718323,1.342742,1.185895,135689.340619
2020-05-01,2.216573,0.581653,1.547801,0.118571,0.030696,0.337028,-0.422132,135693.750808
2020-06-01,0.552825,1.016980,0.436379,0.571846,0.297064,0.423434,0.580018,135697.629355
2020-07-01,2.968301,1.257501,-0.304450,0.458357,0.256106,1.484263,0.241354,135703.990788
2020-08-01,3.024817,0.448239,1.116674,-0.449694,-0.343796,-0.208117,-0.359134,135707.219777
2020-09-01,-1.819236,-0.388196,-0.241857,0.124523,0.104978,0.038144,-0.161556,135704.876577
2020-10-01,-1.136534,-1.064418,-1.036312,-0.275865,-0.178925,-0.133316,-0.451285,135700.599921
2020-11-01,4.855654,2.984232,3.600170,0.375301,0.152638,0.449873,3.307836,135716.325625
2020-12-01,1.346763,0.522352,0.518326,0.162377,0.047563,-0.216131,-0.451961,135718.254913
2021-01-01,-0.185244,-0.058554,0.281723,-0.418470,-0.284830,-0.349969,0.061672,135717.301243
2021-02-01,1.253497,1.114661,0.829692,-0.870595,-0.694846,-1.109356,0.742562,135718.566858
2021-03-01,2.026227,1.617509,1.506719,-0.409551,-0.320169,-0.221713,0.914762,135723.680642
2021-04-01,2.326647,0.703705,0.327785,0.008809,0.029239,-0.518406,0.896064,135727.454485
2021-05-01,0.193900,0.941826,0.678816,0.191170,0.124609,0.892017,0.504351,135730.981174
2021-06-01,0.975580,1.020400,0.039621,0.341219,0.265844,0.250681,0.647123,135734.521641

In [77]:
covid19.to_csv('covid19.csv')

## 2015-2016 Growth Scare: 2015-06-22 ~ 2016-01-18

In [78]:
open_day='2015-06-22'
close_day='2016-01-18'
con1=df_R['date']>=open_day
con2=df_R['date']<=close_day
growth_scare=df_R[con1&con2]
growth_scare

,date,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
111,2015-07-01,0.032855,0.016215,0.053342,0.017291,0.013946,0.026642,0.005533
112,2015-08-01,-0.062423,-0.045581,-0.080418,-0.012011,-0.008945,-0.032051,-0.054291
113,2015-09-01,-0.026719,-0.038987,-0.042414,-0.002418,-0.005602,0.000828,0.017110
114,2015-10-01,0.082358,0.022659,0.068036,-0.003053,-0.001053,-0.019024,0.007168
115,2015-11-01,0.004574,-0.001499,0.017529,0.001108,-0.001108,0.008853,-0.010731
116,2015-12-01,-0.029801,-0.038038,-0.045378,0.011656,0.012662,0.013373,-0.034124
117,2016-01-01,-0.042112,-0.008059,-0.034896,0.002059,0.005715,0.002320,0.007495

In [79]:
growth_scare.to_csv('growth_scare.csv',encoding='utf-8',index=False)

In [80]:
growth_scare=pd.read_csv('growth_scare.csv',index_col=0)
growth_scare

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2015-07-01,0.032855,0.016215,0.053342,0.017291,0.013946,0.026642,0.005533
2015-08-01,-0.062423,-0.045581,-0.080418,-0.012011,-0.008945,-0.032051,-0.054291
2015-09-01,-0.026719,-0.038987,-0.042414,-0.002418,-0.005602,0.000828,0.017110
2015-10-01,0.082358,0.022659,0.068036,-0.003053,-0.001053,-0.019024,0.007168
2015-11-01,0.004574,-0.001499,0.017529,0.001108,-0.001108,0.008853,-0.010731
2015-12-01,-0.029801,-0.038038,-0.045378,0.011656,0.012662,0.013373,-0.034124
2016-01-01,-0.042112,-0.008059,-0.034896,0.002059,0.005715,0.002320,0.007495

In [81]:
XSPTO_R=  df['XSP.TO_P'].iloc[-1] * growth_scare["XSP.TO_R"]
XSPTO_R = XSPTO_R.to_frame(name='XSP.TO_R')

XIUTO_R=  df['XIU.TO_P'].iloc[-1] * growth_scare["XIU.TO_R"]
XIUTO_R = XIUTO_R.to_frame(name='XIU.TO_R')

XINTO_R=  df['XIN.TO_P'].iloc[-1] * growth_scare["XIN.TO_R"]
XINTO_R = XINTO_R.to_frame(name='XIN.TO_R')

XBBTO_R=  df['XBB.TO_P'].iloc[-1] * growth_scare["XBB.TO_R"]
XBBTO_R = XBBTO_R.to_frame(name='XBB.TO_R')

XGBTO_R=  df['XGB.TO_P'].iloc[-1] * growth_scare["XGB.TO_R"]
XGBTO_R = XGBTO_R.to_frame(name='XGB.TO_R')

XRBTO_R=  df['XRB.TO_P'].iloc[-1] * growth_scare["XRB.TO_R"]
XRBTO_R = XRBTO_R.to_frame(name='XRB.TO_R')

XRETO_R=  df['XRE.TO_P'].iloc[-1] * growth_scare["XRE.TO_R"]
XRETO_R = XRETO_R.to_frame(name='XRE.TO_R')

In [82]:
growth_scare = XSPTO_R.merge(XIUTO_R, on='date').merge(XINTO_R, on='date').merge(XBBTO_R, on='date').merge(XGBTO_R, on='date').merge(XRBTO_R, on='date').merge(XRETO_R, on='date')
growth_scare

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2015-07-01,1.509828,0.495036,1.586197,0.550752,0.308590,0.690560,0.106033
2015-08-01,-2.868586,-1.391596,-2.391329,-0.382579,-0.197936,-0.830781,-1.040403
2015-09-01,-1.227866,-1.190261,-1.261220,-0.077012,-0.123954,0.021457,0.327889
2015-10-01,3.784692,0.691781,2.023143,-0.097229,-0.023296,-0.493103,0.137354
2015-11-01,0.210189,-0.045779,0.521244,0.035295,-0.024522,0.229478,-0.205641
2015-12-01,-1.369496,-1.161295,-1.349375,0.371271,0.280172,0.346620,-0.653928
2016-01-01,-1.935232,-0.246056,-1.037664,0.065587,0.126464,0.060145,0.143636

In [87]:
growth_scare["Portfolio"] = growth_scare.sum(axis=1)
growth_scare

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2015-07-01,1.509828,0.495036,1.586197,0.550752,0.308590,0.690560,0.106033,135715.894734
2015-08-01,-2.868586,-1.391596,-2.391329,-0.382579,-0.197936,-0.830781,-1.040403,135692.441320
2015-09-01,-1.227866,-1.190261,-1.261220,-0.077012,-0.123954,0.021457,0.327889,135694.482596
2015-10-01,3.784692,0.691781,2.023143,-0.097229,-0.023296,-0.493103,0.137354,135710.060249
2015-11-01,0.210189,-0.045779,0.521244,0.035295,-0.024522,0.229478,-0.205641,135705.477435
2015-12-01,-1.369496,-1.161295,-1.349375,0.371271,0.280172,0.346620,-0.653928,135697.685106
2016-01-01,-1.935232,-0.246056,-1.037664,0.065587,0.126464,0.060145,0.143636,135695.574900

In [84]:
growth_scare.iloc[0,7]= 5.246995 + 135705.400744
growth_scare

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2015-07-01,1.509828,0.495036,1.586197,0.550752,0.308590,0.690560,0.106033,135710.647739
2015-08-01,-2.868586,-1.391596,-2.391329,-0.382579,-0.197936,-0.830781,-1.040403,-9.103210
2015-09-01,-1.227866,-1.190261,-1.261220,-0.077012,-0.123954,0.021457,0.327889,-3.530967
2015-10-01,3.784692,0.691781,2.023143,-0.097229,-0.023296,-0.493103,0.137354,6.023343
2015-11-01,0.210189,-0.045779,0.521244,0.035295,-0.024522,0.229478,-0.205641,0.720264
2015-12-01,-1.369496,-1.161295,-1.349375,0.371271,0.280172,0.346620,-0.653928,-3.536032
2016-01-01,-1.935232,-0.246056,-1.037664,0.065587,0.126464,0.060145,0.143636,-2.823119

In [85]:
growth_scare['Portfolio'] = np.cumsum(growth_scare['Portfolio'])
growth_scare

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2015-07-01,1.509828,0.495036,1.586197,0.550752,0.308590,0.690560,0.106033,135710.647739
2015-08-01,-2.868586,-1.391596,-2.391329,-0.382579,-0.197936,-0.830781,-1.040403,135701.544529
2015-09-01,-1.227866,-1.190261,-1.261220,-0.077012,-0.123954,0.021457,0.327889,135698.013563
2015-10-01,3.784692,0.691781,2.023143,-0.097229,-0.023296,-0.493103,0.137354,135704.036906
2015-11-01,0.210189,-0.045779,0.521244,0.035295,-0.024522,0.229478,-0.205641,135704.757170
2015-12-01,-1.369496,-1.161295,-1.349375,0.371271,0.280172,0.346620,-0.653928,135701.221138
2016-01-01,-1.935232,-0.246056,-1.037664,0.065587,0.126464,0.060145,0.143636,135698.398019

In [86]:
growth_scare.to_csv('growth_scare.csv')

## Growth Scenario: 2009-03-08 ~ 2010-04-22

In [88]:
open_day='2009-03-08'
close_day='2010-04-22'
con1=df_R['date']>=open_day
con2=df_R['date']<=close_day
growth_scenario=df_R[con1&con2]
growth_scenario

,date,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
36,2009-04-01,0.092455,0.083779,0.098266,0.009797,0.007886,-0.027951,0.110740
37,2009-05-01,0.050584,0.125702,0.052631,0.000000,-0.014017,0.010117,0.143037
38,2009-06-01,-0.012037,-0.013724,-0.030000,0.002400,0.002452,0.010016,0.013172
39,2009-07-01,0.084303,0.050263,0.094972,0.015744,0.010525,0.048166,0.067950
40,2009-08-01,0.033130,-0.001820,0.039497,0.007831,0.008309,-0.007056,0.080042
41,2009-09-01,0.032911,0.035866,0.020150,0.002364,-0.000485,0.002538,0.058710
42,2009-10-01,-0.013889,-0.040629,-0.030474,0.010073,0.007393,0.031393,-0.010885
43,2009-11-01,0.059652,0.059077,0.017462,0.013495,0.013619,0.004909,0.013060
44,2009-12-01,0.007037,0.009297,0.024599,-0.024634,-0.027352,0.003908,0.068140
45,2010-01-01,-0.028141,-0.053515,-0.021739,0.027760,0.027838,0.022395,0.035022
46,2010-02-01,0.031401,0.048959,0.012174,0.001345,-0.000485,-0.012524,0.014370
47,2010-03-01,0.056987,0.032089,0.068156,-0.018457,-0.018932,0.007317,-0.005000
48,2010-04-01,0.014771,0.021728,-0.022520,0.010264,0.006526,0.013559,0.032747

In [89]:
growth_scenario.to_csv('growth_scenario.csv',encoding='utf-8',index=False)

In [90]:
growth_scenario=pd.read_csv('growth_scenario.csv',index_col=0)
growth_scenario

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2009-04-01,0.092455,0.083779,0.098266,0.009797,0.007886,-0.027951,0.110740
2009-05-01,0.050584,0.125702,0.052631,0.000000,-0.014017,0.010117,0.143037
2009-06-01,-0.012037,-0.013724,-0.030000,0.002400,0.002452,0.010016,0.013172
2009-07-01,0.084303,0.050263,0.094972,0.015744,0.010525,0.048166,0.067950
2009-08-01,0.033130,-0.001820,0.039497,0.007831,0.008309,-0.007056,0.080042
2009-09-01,0.032911,0.035866,0.020150,0.002364,-0.000485,0.002538,0.058710
2009-10-01,-0.013889,-0.040629,-0.030474,0.010073,0.007393,0.031393,-0.010885
2009-11-01,0.059652,0.059077,0.017462,0.013495,0.013619,0.004909,0.013060
2009-12-01,0.007037,0.009297,0.024599,-0.024634,-0.027352,0.003908,0.068140
2010-01-01,-0.028141,-0.053515,-0.021739,0.027760,0.027838,0.022395,0.035022
2010-02-01,0.031401,0.048959,0.012174,0.001345,-0.000485,-0.012524,0.014370
2010-03-01,0.056987,0.032089,0.068156,-0.018457,-0.018932,0.007317,-0.005000
2010-04-01,0.014771,0.021728,-0.022520,0.010264,0.006526,0.013559,0.032747

In [91]:
XSPTO_R=  df['XSP.TO_P'].iloc[-1] * growth_scenario["XSP.TO_R"]
XSPTO_R = XSPTO_R.to_frame(name='XSP.TO_R')

XIUTO_R=  df['XIU.TO_P'].iloc[-1] * growth_scenario["XIU.TO_R"]
XIUTO_R = XIUTO_R.to_frame(name='XIU.TO_R')

XINTO_R=  df['XIN.TO_P'].iloc[-1] * growth_scenario["XIN.TO_R"]
XINTO_R = XINTO_R.to_frame(name='XIN.TO_R')

XBBTO_R=  df['XBB.TO_P'].iloc[-1] * growth_scenario["XBB.TO_R"]
XBBTO_R = XBBTO_R.to_frame(name='XBB.TO_R')

XGBTO_R=  df['XGB.TO_P'].iloc[-1] * growth_scenario["XGB.TO_R"]
XGBTO_R = XGBTO_R.to_frame(name='XGB.TO_R')

XRBTO_R=  df['XRB.TO_P'].iloc[-1] * growth_scenario["XRB.TO_R"]
XRBTO_R = XRBTO_R.to_frame(name='XRB.TO_R')

XRETO_R=  df['XRE.TO_P'].iloc[-1] * growth_scenario["XRE.TO_R"]
XRETO_R = XRETO_R.to_frame(name='XRE.TO_R')

In [92]:
growth_scenario = XSPTO_R.merge(XIUTO_R, on='date').merge(XINTO_R, on='date').merge(XBBTO_R, on='date').merge(XGBTO_R, on='date').merge(XRBTO_R, on='date').merge(XRETO_R, on='date')
growth_scenario

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R
date,,,,,,,
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083
2009-10-01,-0.638240,-1.240408,-0.906179,0.320860,0.163580,0.813707,-0.208588
2009-11-01,2.741243,1.803623,0.519259,0.429857,0.301347,0.127243,0.250275
2009-12-01,0.323370,0.283842,0.731488,-0.784642,-0.605210,0.101304,1.305796
2010-01-01,-1.293205,-1.633823,-0.646434,0.884211,0.615972,0.580487,0.671142
2010-02-01,1.442996,1.494728,0.362006,0.042825,-0.010729,-0.324635,0.275377
2010-03-01,2.618770,0.979680,2.026687,-0.587881,-0.418918,0.189664,-0.095825
2010-04-01,0.678781,0.663358,-0.669659,0.326919,0.144402,0.351456,0.627546

In [93]:
growth_scenario["Portfolio"] = growth_scenario.sum(axis=1)
growth_scenario

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160,11.612673
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070,10.420429
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414,-1.221500
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156,11.517688
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873,4.425658
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083,4.461988
2009-10-01,-0.638240,-1.240408,-0.906179,0.320860,0.163580,0.813707,-0.208588,-1.695268
2009-11-01,2.741243,1.803623,0.519259,0.429857,0.301347,0.127243,0.250275,6.172846
2009-12-01,0.323370,0.283842,0.731488,-0.784642,-0.605210,0.101304,1.305796,1.355948
2010-01-01,-1.293205,-1.633823,-0.646434,0.884211,0.615972,0.580487,0.671142,-0.821650
2010-02-01,1.442996,1.494728,0.362006,0.042825,-0.010729,-0.324635,0.275377,3.282569
2010-03-01,2.618770,0.979680,2.026687,-0.587881,-0.418918,0.189664,-0.095825,4.712177
2010-04-01,0.678781,0.663358,-0.669659,0.326919,0.144402,0.351456,0.627546,2.122803

In [94]:
growth_scenario.iloc[0,7]= 11.612673 + 135705.400744
growth_scenario

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160,135717.013417
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070,10.420429
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414,-1.221500
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156,11.517688
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873,4.425658
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083,4.461988
2009-10-01,-0.638240,-1.240408,-0.906179,0.320860,0.163580,0.813707,-0.208588,-1.695268
2009-11-01,2.741243,1.803623,0.519259,0.429857,0.301347,0.127243,0.250275,6.172846
2009-12-01,0.323370,0.283842,0.731488,-0.784642,-0.605210,0.101304,1.305796,1.355948
2010-01-01,-1.293205,-1.633823,-0.646434,0.884211,0.615972,0.580487,0.671142,-0.821650
2010-02-01,1.442996,1.494728,0.362006,0.042825,-0.010729,-0.324635,0.275377,3.282569
2010-03-01,2.618770,0.979680,2.026687,-0.587881,-0.418918,0.189664,-0.095825,4.712177
2010-04-01,0.678781,0.663358,-0.669659,0.326919,0.144402,0.351456,0.627546,2.122803

In [95]:
growth_scenario['Portfolio'] = np.cumsum(growth_scenario['Portfolio'])
growth_scenario

,XSP.TO_R,XIU.TO_R,XIN.TO_R,XBB.TO_R,XGB.TO_R,XRB.TO_R,XRE.TO_R,Portfolio
date,,,,,,,,
2009-04-01,4.248658,2.557774,2.922050,0.312042,0.174483,-0.724494,2.122160,135717.013417
2009-05-01,2.324524,3.837692,1.565056,0.000000,-0.310155,0.262244,2.741070,135727.433846
2009-06-01,-0.553157,-0.418999,-0.892085,0.076455,0.054252,0.259620,0.252414,135726.212346
2009-07-01,3.874052,1.534534,2.824099,0.501486,0.232884,1.248478,1.302156,135737.730035
2009-08-01,1.522457,-0.055569,1.174496,0.249446,0.183861,-0.182906,1.533873,135742.155693
2009-09-01,1.512393,1.095002,0.599175,0.075290,-0.010739,0.065784,1.125083,135746.617680
2009-10-01,-0.638240,-1.240408,-0.906179,0.320860,0.163580,0.813707,-0.208588,135744.922412
2009-11-01,2.741243,1.803623,0.519259,0.429857,0.301347,0.127243,0.250275,135751.095259
2009-12-01,0.323370,0.283842,0.731488,-0.784642,-0.605210,0.101304,1.305796,135752.451207
2010-01-01,-1.293205,-1.633823,-0.646434,0.884211,0.615972,0.580487,0.671142,135751.629557
2010-02-01,1.442996,1.494728,0.362006,0.042825,-0.010729,-0.324635,0.275377,135754.912126
2010-03-01,2.618770,0.979680,2.026687,-0.587881,-0.418918,0.189664,-0.095825,135759.624303
2010-04-01,0.678781,0.663358,-0.669659,0.326919,0.144402,0.351456,0.627546,135761.747106

In [96]:
growth_scenario.to_csv('growth_scenario.csv')